### ISSUE TITLE
Add metadata to `mix.exs`

### ISSUE THREAD

**Issue by stephaniewilkinson** [NAISorg/conrex#1]
https://hex.pm/docs/publish

`:name`
    The name of the package in case you want to publish the package with a different name than the application name. By default this is set to the same as the name of your OTP application (having the same value as `project.app`), written in snake_case (lowercase with underscores as word separator).

`:organization`
    The organization the package belongs to. The package will be published to the organization repository, defaults to the global "hexpm" repository.

`:licenses`
    A list of licenses the project is licensed under. This attribute is required. It is recommended to use SPDX License identifier.

`:links`
    A map where the key is a link name and the value is the link URL. Optional but highly recommended.

`:files`
    A list of files and directories to include in the package. Defaults to standard project directories, so you usually don't need to set this property.

`:build_tools`
    List of build tools that can build the package. It's very rare that you need to set this, as Hex tries to automatically detect the build tools based on the files in the package. If a rebar or rebar.config file is present Hex will mark it as able to build with rebar. This detection can be overridden by setting this field.

**Comment by stephaniewilkinson** [comment]
Can you give me the link to this? i was trying to find it

**Comment by protestContest** [comment]
It's available on your dashboard when you're logged in — https://hex.pm/dashboard/orgs

**Comment by stephaniewilkinson** [comment]
ok kewl it's called 'nais' so you can add it in

**Comment by stephaniewilkinson** [comment]
lmk when this is updated and i'll release it to hex!

**Comment by protestContest** [comment]
Just pushed! `:files` and `:build_tools` weren't needed for this.
